# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndata.proto\"A\n\x0border_place\x12\x13\n\x0b\x62\x65gin_place\x18\x01 \x01(\t\x12\x11\n\tend_place\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\"\x1c\n\x0ereturn_message\x12\n\n\x02ok\x18\x01 \x01(\t26\n\nRouteBuild\x12(\n\x05\x42uild\x12\x0c.order_place\x1a\x0f.return_message\"\x00\x62\x06proto3')
)




_ORDER_PLACE = _descriptor.Descriptor(
  name='order_place',
  full_name='order_place',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin_place', full_name='order_place.begin_place', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_place', full_name='order_place.end_place', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='order_place.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=79,
)


_RETURN_MESSAGE = _descriptor.Descriptor(
  name='return_message',
  full_name='return_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='return_message.ok', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['order_place'] = _ORDER_PLACE
DESCRIPTOR.message_types_by_name['return_message'] = _RETURN_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

order_place = _reflection.GeneratedProtocolMessageType('order_place', (_message.Message,), {
  'DESCRIPTOR' : _ORDER_PLACE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:order_place)
  })
_sym_db.RegisterMessage(order_place)

return_message = _reflection.GeneratedProtocolMessageType('return_message', (_message.Message,), {
  'DESCRIPTOR' : _RETURN_MESSAGE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:return_message)
  })
_sym_db.RegisterMessage(return_message)



_ROUTEBUILD = _descriptor.ServiceDescriptor(
  name='RouteBuild',
  full_name='RouteBuild',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=111,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='Build',
    full_name='RouteBuild.Build',
    index=0,
    containing_service=None,
    input_type=_ORDER_PLACE,
    output_type=_RETURN_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTEBUILD)

DESCRIPTOR.services_by_name['RouteBuild'] = _ROUTEBUILD

# @@protoc_insertion_point(module_scope)
